### ISSUE TITLE
Next JS Type error 

### ISSUE THREAD

**Issue by lucasoz** [sapics/geoip-country#21]
I can't use this library. I am importing the library in this way

```
// middleware.ts
import { NextRequest, NextResponse } from "next/server";
import geoip from "geoip-country";

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();

  try {
    const g = geoip.lookup("181.51.33.40");
    console.log(g);

...
```

```Server Error
TypeError: Cannot read properties of undefined (reading 'length')

This error happened while generating the page. Any console logs will be displayed in the terminal window.

- error Error [TypeError]: Cannot read properties of undefined (reading 'length')
    at <unknown> (webpack-internal:///(middleware)/./node_modules/geoip-country/lib/geoip.js:15)
    at eval (webpack-internal:///(middleware)/./node_modules/geoip-country/lib/geoip.js:15:37)
    at (middleware)/./node_modules/geoip-country/lib/geoip.js (file:///home/lucas/Development/dondo-store-pages/.next/server/middleware.js:116:1)
    at __webpack_require__ (file:///home/lucas/Development/dondo-store-pages/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///home/lucas/Development/dondo-store-pages/.next/server/edge-runtime-webpack.js:280:21)
    at eval (webpack-internal:///(middleware)/./middleware.ts:7:71)
    at (middleware)/./middleware.ts (file:///home/lucas/Development/dondo-store-pages/.next/server/middleware.js:84:1)
    at __webpack_require__ (file:///home/lucas/Development/dondo-store-pages/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///home/lucas/Development/dondo-store-pages/.next/server/edge-runtime-webpack.js:280:21)
    at eval (webpack-internal:///(middleware)/./node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=%2Fhome%2Flucas%2FDevelopment%2Fdondo-store-pages%2Fmiddleware.ts&page=%2Fmiddleware&rootDir=%2Fhome%2Flucas%2FDevelopment%2Fdondo-store-pages&matchers=&preferredRegion=&middlewareConfig=e30%3D!:7:72)
    at (middleware)/./node_modules/next/dist/build/webpack/loaders/next-middleware-loader.js?absolutePagePath=%2Fhome%2Flucas%2FDevelopment%2Fdondo-store-pages%2Fmiddleware.ts&page=%2Fmiddleware&rootDir=%2Fhome%2Flucas%2FDevelopment%2Fdondo-store-pages&matchers=&preferredRegion=&middlewareConfig=e30%3D! (file:///home/lucas/Development/dondo-store-pages/.next/server/middleware.js:73:1) {
  digest: undefined
}
```

**Comment by sapics** [comment]
Thanks for error reporting!
I try to fix error in a newer version. Could you try a newer version?

**Comment by sapics** [comment]
I close this as fixed. If you find any bugs, feel free to reopen this issue or create new issue.
